from __future__ import annotations

import argparse
import json
import os
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .io import read_json


MAIN_CONDITIONS = {
    "behavioral": ("behavioral", "Behavioral control"),
    "explicit_monitor": ("monitor_aware", "Explicit monitor"),
    "a_only": ("a_only", "A-only"),
    "b_only": ("b_only", "B-only"),
    "a_plus_b": ("ab", "A+B"),
}
RATIO_FAMILIES = {
    "a_only": ("a_only", "A-only"),
    "b_only": ("b_only", "B-only"),
    "ab": ("a_plus_b", "A+B"),
    "monitor_aware": ("explicit_monitor", "Explicit monitor"),
}


def _secure_write(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(dir=path.parent, prefix=f".{path.name}.", suffix=".tmp")
    try:
        os.fchmod(descriptor, 0o600)
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            json.dump(value, handle, indent=2, ensure_ascii=False)
            handle.write("\n")
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temporary, path)
        path.chmod(0o600)
    except Exception:
        try:
            os.close(descriptor)
        except OSError:
            pass
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def _epoch_record(manifest_path: Path, epoch: int) -> dict[str, Any]:
    manifest = read_json(manifest_path)
    epochs = manifest.get("epochs", {})
    record = epochs.get(str(epoch))
    if not isinstance(record, dict):
        raise ValueError(f"{manifest_path}: missing epoch {epoch}")
    return record


def checkpoint_uri(manifest_path: Path, epoch: int, kind: str) -> str:
    key = f"{kind}_uri"
    value = _epoch_record(manifest_path, epoch).get(key)
    if not isinstance(value, str) or not value.startswith("tinker://"):
        raise ValueError(f"{manifest_path}: epoch {epoch} is missing {key}")
    marker = "/weights/" if kind == "state" else "/sampler_weights/"
    if marker not in value:
        raise ValueError(f"{manifest_path}: epoch {epoch} has the wrong {kind} URI kind")
    return value


def checkpoints_ready(manifest_path: Path, epochs: list[int]) -> bool:
    if not manifest_path.is_file():
        return False
    try:
        manifest = read_json(manifest_path)
        if manifest.get("status") != "completed":
            return False
        for epoch in epochs:
            checkpoint_uri(manifest_path, epoch, "state")
            checkpoint_uri(manifest_path, epoch, "sampler")
    except (KeyError, TypeError, ValueError, json.JSONDecodeError):
        return False
    return True


def checkpoint_provenance_matches(manifest_path: Path, expected_path: Path) -> bool:
    if not manifest_path.is_file() or not expected_path.is_file():
        return False
    try:
        manifest = read_json(manifest_path)
        expected = read_json(expected_path)
    except (OSError, ValueError, json.JSONDecodeError):
        return False
    return manifest.get("provenance") == expected


def selected_value(path: Path, field: str) -> str:
    payload = read_json(path)
    value = payload.get(field)
    if field == "selected_epoch":
        return str(int(value))
    if not isinstance(value, str) or not value:
        raise ValueError(f"{path}: missing {field}")
    if field == "selected_model" and "/sampler_weights/" not in value:
        raise ValueError(f"{path}: selected_model is not a sampler URI")
    return value


def write_main_manifest(run_dir: Path, output: Path) -> dict[str, Any]:
    conditions: dict[str, Any] = {}
    for launcher_name, (result_key, label) in MAIN_CONDITIONS.items():
        selection = run_dir / "selector" / launcher_name / "selected.json"
        aggregate = run_dir / "full" / launcher_name / "aggregate.json"
        if not selection.is_file() or not aggregate.is_file():
            raise ValueError(f"Incomplete main-run artifacts for {launcher_name}")
        conditions[result_key] = {
            "label": label,
            "selected_epoch": int(selected_value(selection, "selected_epoch")),
            "aggregate": os.path.relpath(aggregate, output.parent),
        }
    manifest = {
        "kind": "main",
        "definition": "Generated by scripts/run_main_experiment.sh from completed aggregates",
        "conditions": conditions,
    }
    _secure_write(output, manifest)
    return manifest


def write_ratio_manifest(run_dir: Path, main_run: Path, output: Path) -> dict[str, Any]:
    families: dict[str, Any] = {}
    for family, (main_condition, label) in RATIO_FAMILIES.items():
        main_selection = main_run / "selector" / main_condition / "selected.json"
        if not main_selection.is_file():
            raise ValueError(f"Main-run selection is missing for {main_condition}")
        points: dict[str, Any] = {
            "0": {
                "selected_epoch": int(selected_value(main_selection, "selected_epoch")),
                "aggregate": os.path.relpath(
                    run_dir / "endpoints" / f"{family}_behavioral_0_aggregate.json", output.parent
                ),
            }
        }
        for percentage in (25, 50, 75):
            arm = f"{family}_behavioral_{percentage}"
            selection = run_dir / "selector" / arm / "selected.json"
            aggregate = run_dir / "full" / arm / "aggregate.json"
            if not selection.is_file() or not aggregate.is_file():
                raise ValueError(f"Incomplete ratio-run artifacts for {arm}")
            points[str(percentage)] = {
                "selected_epoch": int(selected_value(selection, "selected_epoch")),
                "aggregate": os.path.relpath(aggregate, output.parent),
            }
        behavioral_selection = main_run / "selector" / "behavioral" / "selected.json"
        points["100"] = {
            "selected_epoch": int(selected_value(behavioral_selection, "selected_epoch")),
            "aggregate": os.path.relpath(
                run_dir / "endpoints" / "behavioral_100_aggregate.json", output.parent
            ),
        }
        families[family] = {"label": label, "points": points}
    manifest = {
        "kind": "ratio",
        "definition": "Generated by scripts/run_ratio_ablation.sh from completed aggregates",
        "families": families,
    }
    _secure_write(output, manifest)
    return manifest


def record_run(run_dir: Path, kind: str, status: str) -> dict[str, Any]:
    path = run_dir / "run.json"
    existing = read_json(path) if path.is_file() else {}
    now = datetime.now(timezone.utc).isoformat()
    record = {
        "schema_version": 1,
        "kind": kind,
        "status": status,
        "created_at_utc": existing.get("created_at_utc", now),
        "updated_at_utc": now,
    }
    _secure_write(path, record)
    return record


def main() -> None:
    parser = argparse.ArgumentParser(description="Private run-manifest helpers for the shell workflows")
    subparsers = parser.add_subparsers(dest="command", required=True)

    ready = subparsers.add_parser("checkpoints-ready")
    ready.add_argument("manifest", type=Path)
    ready.add_argument("--epochs", type=int, nargs="+", required=True)

    provenance = subparsers.add_parser("provenance-matches")
    provenance.add_argument("manifest", type=Path)
    provenance.add_argument("--expected", type=Path, required=True)

    uri = subparsers.add_parser("checkpoint-uri")
    uri.add_argument("manifest", type=Path)
    uri.add_argument("--epoch", type=int, required=True)
    uri.add_argument("--kind", choices=("state", "sampler"), required=True)

    selected = subparsers.add_parser("selected-value")
    selected.add_argument("selection", type=Path)
    selected.add_argument("--field", choices=("selected_epoch", "selected_model"), required=True)

    main_manifest = subparsers.add_parser("write-main-manifest")
    main_manifest.add_argument("--run-dir", type=Path, required=True)
    main_manifest.add_argument("--output", type=Path, required=True)

    ratio_manifest = subparsers.add_parser("write-ratio-manifest")
    ratio_manifest.add_argument("--run-dir", type=Path, required=True)
    ratio_manifest.add_argument("--main-run", type=Path, required=True)
    ratio_manifest.add_argument("--output", type=Path, required=True)

    run = subparsers.add_parser("record-run")
    run.add_argument("--run-dir", type=Path, required=True)
    run.add_argument("--kind", choices=("main", "ratio"), required=True)
    run.add_argument("--status", choices=("running", "completed"), required=True)

    args = parser.parse_args()
    if args.command == "checkpoints-ready":
        raise SystemExit(0 if checkpoints_ready(args.manifest, args.epochs) else 1)
    if args.command == "provenance-matches":
        raise SystemExit(0 if checkpoint_provenance_matches(args.manifest, args.expected) else 1)
    if args.command == "checkpoint-uri":
        print(checkpoint_uri(args.manifest, args.epoch, args.kind))
    elif args.command == "selected-value":
        print(selected_value(args.selection, args.field))
    elif args.command == "write-main-manifest":
        write_main_manifest(args.run_dir, args.output)
        print(f"wrote {args.output}")
    elif args.command == "write-ratio-manifest":
        write_ratio_manifest(args.run_dir, args.main_run, args.output)
        print(f"wrote {args.output}")
    elif args.command == "record-run":
        record_run(args.run_dir, args.kind, args.status)
        print(f"recorded {args.kind} run status: {args.status}")


if __name__ == "__main__":
    main()
